name: Deploy to GitHub Pages

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'

      - name: Publish
        run: dotnet publish -c Release -o publish

      - name: Fix base path & 404
        run: |
          sed -i 's|<base href="/" />|<base href="/YOUR-REPO-NAME/" />|g' publish/wwwroot/index.html
          cp publish/wwwroot/index.html publish/wwwroot/404.html
          touch publish/wwwroot/.nojekyll

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: publish/wwwroot
